# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tuwien_logon}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Clemens Helm"]
  s.date = %q{2010-04-15}
  s.description = %q{Provides an authentication solution for ruby applications being used at the Vienna University of Technology}
  s.email = %q{clemens.helm@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/tuwien_logon.rb",
     "lib/tuwien_logon/configuration.rb",
     "lib/tuwien_logon/user_info.rb",
     "lib/tuwien_logon/user_info_request.rb",
     "test/helper.rb",
     "test/test_tuwien_logon.rb",
     "test/test_user_info.rb",
     "test/test_user_info_request.rb",
     "tuwien_logon.gemspec"
  ]
  s.homepage = %q{http://github.com/dropswap/tuwien_logon}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Ruby client for Vienna UT authentication service}
  s.test_files = [
    "test/helper.rb",
     "test/test_tuwien_logon.rb",
     "test/test_user_info.rb",
     "test/test_user_info_request.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

